import 'package:flutter/material.dart';
import 'EquipmentItem.dart';

final List<EquipmentItem> fakeDataList = [
  EquipmentItem(
    id: "e2",
    categories: ["Electronics", "Mobile"],
    type: "Smartphone",
    title: "Smartphone",
    pricePerHour: 1.0,
    pricePerDay: 7.0,
    pricePerWeek: 15.0,
    pricePerMonth: 50.0,
    pricePerYear: 500.0,
    condition: Condition.newCondition,
    rentalType: RentalType.hourly,
    icon: Icons.phone_android,
    description: "Latest model smartphone",
    specs: ["6.1 inch", "128GB Storage", "Dual Camera"],
    images: [],
    rating: 4.6,
    reviews: 89,
    likes: 67,
    rentedCount: 45,
    latitude: 31.96,
    longitude: 35.94,
    status: ProductStatus.rented,
  ),

  EquipmentItem(
    id: "e3",
    categories: ["Electronics", "Audio"],
    type: "Headphones",
    title: "Headphones",
    pricePerHour: 0.5,
    pricePerDay: 3.0,
    pricePerWeek: 8.0,
    pricePerMonth: 25.0,
    pricePerYear: 250.0,
    condition: Condition.good,
    rentalType: RentalType.hourly,
    icon: Icons.headphones,
    description: "Noise-cancelling headphones",
    specs: ["Wireless", "20h Battery", "Bluetooth 5.2"],
    images: [],
    rating: 4.3,
    reviews: 34,
    likes: 28,
    rentedCount: 19,
    latitude: 31.98,
    longitude: 35.90,
    status: ProductStatus.available,
  ),

  EquipmentItem(
    id: "e5",
    categories: ["Electronics", "Wearables"],
    type: "Smartwatch",
    title: "Smartwatch",
    pricePerHour: 0.7,
    pricePerDay: 4.0,
    pricePerWeek: 12.0,
    pricePerMonth: 35.0,
    pricePerYear: 350.0,
    condition: Condition.newCondition,
    rentalType: RentalType.hourly,
    icon: Icons.watch,
    description: "Smartwatch with fitness tracking",
    specs: ["Heart Rate Monitor", "GPS", "Water Resistant"],
    images: [],
    rating: 4.7,
    reviews: 56,
    likes: 44,
    rentedCount: 31,
    latitude: 31.97,
    longitude: 35.91,
    status: ProductStatus.available,
  ),

  EquipmentItem(
    id: "e6",
    categories: ["Electronics", "Gaming"],
    type: "Gaming PC",
    title: "Gaming PC",
    pricePerHour: 3.0,
    pricePerDay: 20.0,
    pricePerWeek: 50.0,
    pricePerMonth: 150.0,
    pricePerYear: 1500.0,
    condition: Condition.newCondition,
    rentalType: RentalType.hourly,
    icon: Icons.desktop_windows,
    description: "High performance gaming PC",
    specs: ["RTX 4070", "16GB RAM", "1TB SSD", "i7 Processor"],
    images: [],
    rating: 4.9,
    reviews: 78,
    likes: 92,
    rentedCount: 38,
    latitude: 31.94,
    longitude: 35.89,
    status: ProductStatus.rented,
  ),

  EquipmentItem(
    id: "e7",
    categories: ["Electronics", "Office"],
    type: "Printer",
    title: "Printer",
    pricePerHour: 0.8,
    pricePerDay: 5.0,
    pricePerWeek: 15.0,
    pricePerMonth: 45.0,
    pricePerYear: 450.0,
    condition: Condition.good,
    rentalType: RentalType.weekly,
    icon: Icons.print,
    description: "Color printer for home or office",
    specs: ["Wireless", "Color Printing", "Scanner"],
    images: [],
    rating: 4.2,
    reviews: 29,
    likes: 18,
    rentedCount: 14,
    latitude: 31.96,
    longitude: 35.87,
    status: ProductStatus.available,
  ),

  EquipmentItem(
    id: "e11",
    categories: ["Sports", "Outdoor"],
    type: "Bicycle",
    title: "Bicycle",
    pricePerHour: 1.0,
    pricePerDay: 6.0,
    pricePerWeek: 18.0,
    pricePerMonth: 55.0,
    pricePerYear: 550.0,
    condition: Condition.good,
    rentalType: RentalType.hourly,
    icon: Icons.directions_bike,
    description: "Mountain bike for outdoor adventures",
    specs: ["21 Gears", "Aluminum Frame", "Front Suspension"],
    images: [],
    rating: 4.5,
    reviews: 63,
    likes: 47,
    rentedCount: 35,
    latitude: 31.93,
    longitude: 35.92,
    status: ProductStatus.available,
  ),

  EquipmentItem(
    id: "e12",
    categories: ["Sports", "Camping"],
    type: "Tent",
    title: "Tent",
    pricePerHour: 1.5,
    pricePerDay: 10.0,
    pricePerWeek: 25.0,
    pricePerMonth: 70.0,
    pricePerYear: 700.0,
    condition: Condition.newCondition,
    rentalType: RentalType.weekly,
    icon: Icons.home_work,
    description: "Camping tent for 2 people",
    specs: ["2 Person", "Waterproof", "Easy Setup"],
    images: [],
    rating: 4.6,
    reviews: 45,
    likes: 33,
    rentedCount: 27,
    latitude: 31.92,
    longitude: 35.90,
    status: ProductStatus.rented,
  ),

  EquipmentItem(
    id: "e16",
    categories: ["Tools", "Construction"],
    type: "Hammer",
    title: "Hammer",
    pricePerHour: 0.3,
    pricePerDay: 2.0,
    pricePerWeek: 5.0,
    pricePerMonth: 15.0,
    pricePerYear: 150.0,
    condition: Condition.good,
    rentalType: RentalType.hourly,
    icon: Icons.build,
    description: "Durable hammer for construction work",
    specs: ["Fiberglass Handle", "16oz Head", "Comfort Grip"],
    images: [],
    rating: 4.1,
    reviews: 22,
    likes: 15,
    rentedCount: 12,
    latitude: 31.95,
    longitude: 35.86,
    status: ProductStatus.available,
  ),

  EquipmentItem(
    id: "e17",
    categories: ["Tools", "Power Tools"],
    type: "Drill",
    title: "Drill",
    pricePerHour: 1.0,
    pricePerDay: 6.0,
    pricePerWeek: 18.0,
    pricePerMonth: 50.0,
    pricePerYear: 500.0,
    condition: Condition.newCondition,
    rentalType: RentalType.hourly,
    icon: Icons.construction,
    description: "Electric drill with multiple bits",
    specs: ["Cordless", "18V Battery", "LED Light", "2 Speed Gears"],
    images: [],
    rating: 4.7,
    reviews: 58,
    likes: 42,
    rentedCount: 29,
    latitude: 31.94,
    longitude: 35.88,
    status: ProductStatus.rented,
  ),
];

List<EquipmentItem> getAllEquipment() {
  return [...allEquipments, ...fakeDataList];
}
