import 'package:flutter/material.dart';
import 'EquipmentItem.dart';

final DUMMY_EQUIPMENT = [
  // Electronics (c1)
  EquipmentItem(id: 'e1', categories: ['c1'], title: 'Laptop', pricePerDay: 20.0,
      condition: Condition.good, rentalType: RentalType.daily, icon: Icons.laptop,
      description: 'A good laptop for work and study', type: ''),
  EquipmentItem(id: 'e2', categories: ['c1'], title: 'Smartphone', pricePerDay: 10.0,
      condition: Condition.newCondition, rentalType: RentalType.daily, icon: Icons.phone_android,
      description: 'Latest model smartphone', type: ''),
  EquipmentItem(id: 'e3', categories: ['c1'], title: 'Headphones', pricePerDay: 5.0,
      condition: Condition.good, rentalType: RentalType.daily, icon: Icons.headphones,
      description: 'Noise-cancelling headphones', type: ''),
  EquipmentItem(id: 'e4', categories: ['c1'], title: 'Tablet', pricePerDay: 12.0,
      condition: Condition.good, rentalType: RentalType.weekly, icon: Icons.tablet,
      description: 'Lightweight tablet for study or work', type: ''),
  EquipmentItem(id: 'e5', categories: ['c1'], title: 'Smartwatch', pricePerDay: 7.0,
      condition: Condition.newCondition, rentalType: RentalType.daily, icon: Icons.watch,
      description: 'Smartwatch with fitness tracking', type: ''),
  EquipmentItem(id: 'e31', categories: ['c1'], title: 'Bluetooth Speaker', pricePerDay: 6.0,
      condition: Condition.good, rentalType: RentalType.daily, icon: Icons.speaker,
      description: 'Portable Bluetooth speaker', type: ''),
  EquipmentItem(id: 'e32', categories: ['c1'], title: 'Monitor', pricePerDay: 15.0,
      condition: Condition.good, rentalType: RentalType.daily, icon: Icons.tv,
      description: 'Full HD monitor', type: ''),
  EquipmentItem(id: 'e33', categories: ['c1'], title: 'Keyboard', pricePerDay: 3.0,
      condition: Condition.good, rentalType: RentalType.daily, icon: Icons.keyboard,
      description: 'Mechanical keyboard', type: ''),
  EquipmentItem(id: 'e34', categories: ['c1'], title: 'Mouse', pricePerDay: 2.0,
      condition: Condition.good, rentalType: RentalType.daily, icon: Icons.mouse,
      description: 'Wireless mouse', type: ''),
  EquipmentItem(id: 'e35', categories: ['c1'], title: 'Charger', pricePerDay: 1.0,
      condition: Condition.good, rentalType: RentalType.daily, icon: Icons.power,
      description: 'Fast charger for devices', type: ''),

  // Computers & Technology (c2)
  EquipmentItem(id: 'e6', categories: ['c2'], title: 'Gaming PC', pricePerDay: 30.0,
      condition: Condition.newCondition, rentalType: RentalType.daily, icon: Icons.desktop_windows,
      description: 'High performance gaming PC', type: ''),
  EquipmentItem(id: 'e7', categories: ['c2'], title: 'Printer', pricePerDay: 8.0,
      condition: Condition.good, rentalType: RentalType.weekly, icon: Icons.print,
      description: 'Color printer for home or office', type: ''),
  EquipmentItem(id: 'e8', categories: ['c2'], title: 'Router', pricePerDay: 5.0,
      condition: Condition.good, rentalType: RentalType.daily, icon: Icons.router,
      description: 'High speed Wi-Fi router', type: ''),
  EquipmentItem(id: 'e9', categories: ['c2'], title: 'External Hard Drive', pricePerDay: 6.0,
      condition: Condition.good, rentalType: RentalType.daily, icon: Icons.storage,
      description: '1TB portable hard drive', type: ''),
  EquipmentItem(id: 'e10', categories: ['c2'], title: 'Webcam', pricePerDay: 4.0,
      condition: Condition.newCondition, rentalType: RentalType.daily, icon: Icons.videocam,
      description: 'HD webcam for video calls', type: ''),
  EquipmentItem(id: 'e36', categories: ['c2'], title: 'Graphics Card', pricePerDay: 25.0,
      condition: Condition.newCondition, rentalType: RentalType.daily, icon: Icons.memory,
      description: 'High-end GPU for gaming', type: ''),
  EquipmentItem(id: 'e37', categories: ['c2'], title: 'SSD', pricePerDay: 7.0,
      condition: Condition.good, rentalType: RentalType.daily, icon: Icons.sd_storage,
      description: '500GB Solid State Drive', type: ''),
  EquipmentItem(id: 'e38', categories: ['c2'], title: 'RAM', pricePerDay: 4.0,
      condition: Condition.good, rentalType: RentalType.daily, icon: Icons.sd_card,
      description: '16GB DDR4 RAM', type: ''),
  EquipmentItem(id: 'e39', categories: ['c2'], title: 'Motherboard', pricePerDay: 10.0,
      condition: Condition.good, rentalType: RentalType.daily, icon: Icons.developer_board,
      description: 'ATX Motherboard', type: ''),
  EquipmentItem(id: 'e40', categories: ['c2'], title: 'Power Supply', pricePerDay: 6.0,
      condition: Condition.good, rentalType: RentalType.daily, icon: Icons.battery_charging_full,
      description: '600W Power Supply', type: ''),

  // Sports & Camping (c3)
  EquipmentItem(id: 'e11', categories: ['c3'], title: 'Bicycle', pricePerDay: 10.0,
      condition: Condition.good, rentalType: RentalType.daily, icon: Icons.directions_bike,
      description: 'Mountain bike for outdoor adventures', type: ''),
  EquipmentItem(id: 'e12', categories: ['c3'], title: 'Tent', pricePerDay: 15.0,
      condition: Condition.newCondition, rentalType: RentalType.weekly, icon: Icons.home_work,
      description: 'Camping tent for 2 people', type: ''),
  EquipmentItem(id: 'e13', categories: ['c3'], title: 'Sleeping Bag', pricePerDay: 5.0,
      condition: Condition.good, rentalType: RentalType.daily, icon: Icons.bed,
      description: 'Comfortable sleeping bag', type: ''),
  EquipmentItem(id: 'e14', categories: ['c3'], title: 'Hiking Backpack', pricePerDay: 6.0,
      condition: Condition.good, rentalType: RentalType.daily, icon: Icons.backpack,
      description: 'Durable backpack for hiking trips', type: ''),
  EquipmentItem(id: 'e15', categories: ['c3'], title: 'Camping Stove', pricePerDay: 7.0,
      condition: Condition.newCondition, rentalType: RentalType.daily, icon: Icons.kitchen,
      description: 'Portable stove for outdoor cooking', type: ''),
  EquipmentItem(id: 'e41', categories: ['c3'], title: 'Sleeping Pad', pricePerDay: 4.0,
      condition: Condition.good, rentalType: RentalType.daily, icon: Icons.airline_seat_flat,
      description: 'Comfortable sleeping pad', type: ''),
  EquipmentItem(id: 'e42', categories: ['c3'], title: 'Climbing Rope', pricePerDay: 8.0,
      condition: Condition.newCondition, rentalType: RentalType.daily, icon: Icons.handyman,
      description: 'Strong climbing rope', type: ''),
  EquipmentItem(id: 'e43', categories: ['c3'], title: 'Water Bottle', pricePerDay: 2.0,
      condition: Condition.good, rentalType: RentalType.daily, icon: Icons.local_drink,
      description: 'Reusable water bottle', type: ''),
  EquipmentItem(id: 'e44', categories: ['c3'], title: 'Flashlight', pricePerDay: 3.0,
      condition: Condition.good, rentalType: RentalType.daily, icon: Icons.flashlight_on,
      description: 'Bright LED flashlight', type: ''),
  EquipmentItem(id: 'e45', categories: ['c3'], title: 'Compass', pricePerDay: 1.0,
      condition: Condition.good, rentalType: RentalType.daily, icon: Icons.explore,
      description: 'Navigation compass', type: ''),

  // Tools & Equipment (c4)
  EquipmentItem(id: 'e16', categories: ['c4'], title: 'Hammer', pricePerDay: 3.0,
      condition: Condition.good, rentalType: RentalType.daily, icon: Icons.build,
      description: 'Durable hammer for construction work', type: ''),
  EquipmentItem(id: 'e17', categories: ['c4'], title: 'Drill', pricePerDay: 10.0,
      condition: Condition.newCondition, rentalType: RentalType.daily, icon: Icons.construction,
      description: 'Electric drill with multiple bits', type: ''),
  EquipmentItem(id: 'e18', categories: ['c4'], title: 'Saw', pricePerDay: 8.0,
      condition: Condition.good, rentalType: RentalType.daily, icon: Icons.cut,
      description: 'Hand saw for wood cutting', type: ''),
  EquipmentItem(id: 'e19', categories: ['c4'], title: 'Screwdriver Set', pricePerDay: 4.0,
      condition: Condition.good, rentalType: RentalType.daily, icon: Icons.build_circle,
      description: 'Set of screwdrivers with multiple heads', type: ''),
  EquipmentItem(id: 'e20', categories: ['c4'], title: 'Ladder', pricePerDay: 12.0,
      condition: Condition.good, rentalType: RentalType.daily, icon: Icons.format_line_spacing,
      description: 'Aluminum ladder, foldable', type: ''),
  EquipmentItem(id: 'e46', categories: ['c4'], title: 'Wrench', pricePerDay: 3.0,
      condition: Condition.good, rentalType: RentalType.daily, icon: Icons.handyman,
      description: 'Adjustable wrench', type: ''),
  EquipmentItem(id: 'e47', categories: ['c4'], title: 'Pliers', pricePerDay: 2.0,
      condition: Condition.good, rentalType: RentalType.daily, icon: Icons.plumbing,
      description: 'Set of pliers', type: ''),
  EquipmentItem(id: 'e48', categories: ['c4'], title: 'Tape Measure', pricePerDay: 1.0,
      condition: Condition.good, rentalType: RentalType.daily, icon: Icons.straighten,
      description: 'Measuring tape', type: ''),
  EquipmentItem(id: 'e49', categories: ['c4'], title: 'Level', pricePerDay: 2.0,
      condition: Condition.good, rentalType: RentalType.daily, icon: Icons.square_foot,
      description: 'Spirit level', type: ''),
  EquipmentItem(id: 'e50', categories: ['c4'], title: 'Chisel', pricePerDay: 2.0,
      condition: Condition.good, rentalType: RentalType.daily, icon: Icons.gavel,
      description: 'Wood chisel', type: ''),

  // Garden & Home (c5)
  EquipmentItem(id: 'e21', categories: ['c5'], title: 'Lawn Mower', pricePerDay: 25.0,
      condition: Condition.good, rentalType: RentalType.weekly, icon: Icons.grass,
      description: 'Electric lawn mower for garden', type: ''),
  EquipmentItem(id: 'e22', categories: ['c5'], title: 'Hedge Trimmer', pricePerDay: 12.0,
      condition: Condition.good, rentalType: RentalType.daily, icon: Icons.grass,
      description: 'Electric hedge trimmer', type: ''),
  EquipmentItem(id: 'e23', categories: ['c5'], title: 'Garden Hose', pricePerDay: 5.0,
      condition: Condition.good, rentalType: RentalType.daily, icon: Icons.water_drop,
      description: 'Flexible garden hose, 20m', type: ''),
  EquipmentItem(id: 'e24', categories: ['c5'], title: 'Wheelbarrow', pricePerDay: 15.0,
      condition: Condition.good, rentalType: RentalType.daily, icon: Icons.restore_page,
      description: 'Metal wheelbarrow for garden work', type: ''),
  EquipmentItem(id: 'e25', categories: ['c5'], title: 'Shovel', pricePerDay: 4.0,
      condition: Condition.good, rentalType: RentalType.daily, icon: Icons.agriculture,
      description: 'Sturdy shovel for digging', type: ''),
  EquipmentItem(id: 'e51', categories: ['c5'], title: 'Rake', pricePerDay: 3.0,
      condition: Condition.good, rentalType: RentalType.daily, icon: Icons.grass,
      description: 'Garden rake for leaves', type: ''),
  EquipmentItem(id: 'e52', categories: ['c5'], title: 'Sprinkler', pricePerDay: 2.0,
      condition: Condition.good, rentalType: RentalType.daily, icon: Icons.grass,
      description: 'Automatic lawn sprinkler', type: ''),
  EquipmentItem(id: 'e53', categories: ['c5'], title: 'Pruner', pricePerDay: 2.0,
      condition: Condition.good, rentalType: RentalType.daily, icon: Icons.cut,
      description: 'Hand pruner for plants', type: ''),
  EquipmentItem(id: 'e54', categories: ['c5'], title: 'Garden Gloves', pricePerDay: 1.0,
      condition: Condition.good, rentalType: RentalType.daily, icon: Icons.checkroom,
      description: 'Protective gloves for gardening', type: ''),
  EquipmentItem(id: 'e55', categories: ['c5'], title: 'Compost Bin', pricePerDay: 5.0,
      condition: Condition.good, rentalType: RentalType.daily, icon: Icons.recycling,
      description: 'Bin for composting organic waste', type: ''),

  // Clothing & Fashion (c6)
  EquipmentItem(id: 'e26', categories: ['c6'], title: 'Jacket', pricePerDay: 6.0,
      condition: Condition.newCondition, rentalType: RentalType.daily, icon: Icons.checkroom,
      description: 'Warm jacket for winter', type: ''),
  EquipmentItem(id: 'e27', categories: ['c6'], title: 'Shoes', pricePerDay: 5.0,
      condition: Condition.newCondition, rentalType: RentalType.daily, icon: Icons.checkroom,
      description: 'Comfortable running shoes', type: ''),
  EquipmentItem(id: 'e28', categories: ['c6'], title: 'Hat', pricePerDay: 3.0,
      condition: Condition.good, rentalType: RentalType.daily, icon: Icons.checkroom,
      description: 'Fashionable cap', type: ''),
  EquipmentItem(id: 'e29', categories: ['c6'], title: 'Scarf', pricePerDay: 2.0,
      condition: Condition.good, rentalType: RentalType.daily, icon: Icons.checkroom,
      description: 'Wool scarf for cold weather', type: ''),
  EquipmentItem(id: 'e30', categories: ['c6'], title: 'Gloves', pricePerDay: 2.0,
      condition: Condition.good, rentalType: RentalType.daily, icon: Icons.checkroom,
      description: 'Warm gloves for winter', type: ''),
  EquipmentItem(id: 'e56', categories: ['c6'], title: 'T-Shirt', pricePerDay: 2.0,
      condition: Condition.newCondition, rentalType: RentalType.daily, icon: Icons.checkroom,
      description: 'Cotton t-shirt', type: ''),
  EquipmentItem(id: 'e57', categories: ['c6'], title: 'Jeans', pricePerDay: 3.0,
      condition: Condition.newCondition, rentalType: RentalType.daily, icon: Icons.checkroom,
      description: 'Denim jeans', type: ''),
  EquipmentItem(id: 'e58', categories: ['c6'], title: 'Sweater', pricePerDay: 4.0,
      condition: Condition.good, rentalType: RentalType.daily, icon: Icons.checkroom,
      description: 'Wool sweater', type: ''),
  EquipmentItem(id: 'e59', categories: ['c6'], title: 'Belt', pricePerDay: 1.0,
      condition: Condition.good, rentalType: RentalType.daily, icon: Icons.checkroom,
      description: 'Leather belt', type: ''),
  EquipmentItem(id: 'e60', categories: ['c6'], title: 'Socks', pricePerDay: 1.0,
      condition: Condition.good, rentalType: RentalType.daily, icon: Icons.checkroom,
      description: 'Pair of socks', type: ''),
];
